name: Automated Publish for Insider

on:
  push:
    branches:
      - master

env: 
  AZURE_DEVOPS_PERSONAL_ACCESS_TOKEN: ${{ secrets.AZURE_DEVOPS_PERSONAL_ACCESS_TOKEN }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  PRODUCTION: ${{ secrets.PRODUCTION }}
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs: 
  publish-insider:
    name: Publish Insider
    runs-on: ubuntu-latest
    if: endsWith(github.ref, '/master')
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      - name: Bump version
        run: yarn vsce:bump:insider
        id: bump_insider
      - name: Compile
        run: yarn compile
      - name: Run headless e2e tests
        uses: GabrielBB/xvfb-action@v1.0
        with:
          run: npm run test
      - name: Publish Extension as Patch
        if: ${{ success()}}
        run: yarn vsce:publish "dev"
      - name: Slack Notification on Failure
        if: ${{ failure() && steps.check_for_updates.outputs.new_updates }}
        uses: rtCamp/action-slack-notify@v2.0.2
        env:  
          SLACK_CHANNEL: feed-vscode
          SLACK_TITLE: "Publishing Insider Version failed :x:"
          SLACK_MESSAGE: ${{ steps.bump_insider.outputs.version }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_ICON_EMOJI: ":ship:"
          SLACK_USERNAME: vscode-actions
          SLACK_COLOR: '#FF0000'
      - name: Slack Notification on Success
        if: ${{ success() && steps.check_for_updates.outputs.new_updates }}
        uses: rtCamp/action-slack-notify@v2.0.2
        env:  
          SLACK_CHANNEL: feed-vscode
          SLACK_TITLE: "Published Insider Version :white_check_mark:"
          SLACK_MESSAGE: ${{ steps.bump_insider.outputs.version }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_ICON_EMOJI: ":ship:"
          SLACK_USERNAME: vscode-actions
          SLACK_COLOR: '#008000'